import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // The icons live in public/ and are generated by `npm run icons`.
      includeAssets: ['favicon.svg', 'favicon-32x32.png', 'apple-touch-icon.png'],
      manifest: {
        name: 'Larder',
        short_name: 'Groceries',
        description: 'A realtime household grocery list.',
        display: 'standalone',
        orientation: 'portrait',
        theme_color: '#27583c',
        background_color: '#f2f8f4',
        start_url: '/',
        scope: '/',
        lang: 'en',
        categories: ['shopping', 'productivity', 'lifestyle'],
        icons: [
          { src: '/pwa-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/pwa-maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Deliberately excludes public/icons/**: ten accent sets is ~50 icons
        // and pushed the precache past 950 KB, most of it colours nobody chose.
        // The active accent's icons are fetched on demand and cached at
        // runtime below, so an install costs one set rather than all ten.
        globPatterns: ['**/*.{js,css,html,ico,woff2}', 'pwa-*.png', 'apple-touch-icon.png', 'favicon*'],
        globIgnores: ['**/icons/**'],
        // Deep links must fall back to the app shell, or a hard refresh on
        // /h/<id> is a 404 from the service worker as well as from the host.
        navigateFallback: '/index.html',
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
        // Never cache API traffic. A cached grocery list that looks live is
        // worse than an honest offline banner, and Supabase auth responses
        // must not be replayed from disk.
        navigateFallbackDenylist: [/^\/functions\//, /^\/rest\//, /^\/auth\//],
        runtimeCaching: [
          {
            urlPattern: ({ sameOrigin, url }) => sameOrigin && url.pathname.startsWith('/assets/'),
            handler: 'StaleWhileRevalidate',
            options: { cacheName: 'larder-assets' },
          },
          {
            // Only the accent actually in use ends up cached.
            urlPattern: ({ sameOrigin, url }) => sameOrigin && url.pathname.startsWith('/icons/'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'larder-accent-icons',
              expiration: { maxEntries: 12, maxAgeSeconds: 60 * 60 * 24 * 90 },
            },
          },
        ],
      },
      devOptions: {
        // Keep the service worker out of the way during development.
        enabled: false,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    port: 5173,
    host: true,
  },
})
